[[constraint]]
  branch = "master"
  name = "github.com/aaron-lebo/ocd"

[[constraint]]
  branch = "master"
  name = "github.com/igungor/telegram"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "master"
  name = "github.com/wcharczuk/go-chart"
